version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: bitnami/laravel:latest
        restart: unless-stopped
        working_dir: /app
        ports:
            - "8008:8008"
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: qrcode
        ports:
            - "3333:3306"
