version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8008:8008"
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: qrcode
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
